"""
Codebase Unpacker / Restorer
Reconstructs the full directory structure and files from a packed .txt file
(e.g., modified by Gemini or another LLM).
"""

import os
import sys
import re

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

# Flexible regex to match file headers created by packer or generated by LLMs:
# Matches patterns like:
# ================================================================================
# FILE: path/to/file.py
# ================================================================================
FILE_HEADER_REGEX = re.compile(
    r'(?:^|\n)(?:={10,}|#{1,6}\s*FILE:?)\s*\n'
    r'(?:FILE|PATH):\s*([^\n\r]+?)\s*\n'
    r'={10,}\s*\n',
    re.IGNORECASE
)

# Alternative fallback pattern if LLMs format it like:
# === FILE: path/to/file.py ===
ALT_HEADER_REGEX = re.compile(
    r'(?:^|\n)[=#-]{3,}\s*(?:FILE|PATH):\s*([^\n\r]+?)\s*[=#-]{3,}\s*\n',
    re.IGNORECASE
)


def unpack_codebase(txt_file_path, target_dir=None, dry_run=False):
    if target_dir is None:
        target_dir = ROOT_DIR

    if not os.path.isfile(txt_file_path):
        print(f"Error: Input file '{txt_file_path}' does not exist.")
        return

    print(f"Reading: {txt_file_path}")
    with open(txt_file_path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    # Find all file splits
    matches = list(FILE_HEADER_REGEX.finditer(content))
    if not matches:
        matches = list(ALT_HEADER_REGEX.finditer(content))

    if not matches:
        print("Error: Could not find any FILE: delimiters in the text file.")
        print("Expected header format:")
        print("================================================================================")
        print("FILE: relative/path/to/file.py")
        print("================================================================================")
        return

    print(f"Found {len(matches)} files to extract into: {target_dir}\n")

    created_count = 0
    updated_count = 0

    for i, match in enumerate(matches):
        raw_rel_path = match.group(1).strip().strip("`'\"")
        # Normalize path separators
        rel_path = os.path.normpath(raw_rel_path)

        # Skip dangerous paths attempting to escape target_dir
        if rel_path.startswith("..") or os.path.isabs(rel_path):
            print(f"Skipping potentially unsafe path: {raw_rel_path}")
            continue

        # Extract content between this header and next header (or end of file)
        content_start = match.end()
        content_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        file_content = content[content_start:content_end]

        # Strip any trailing delimiter borders from the end
        file_content = re.sub(r'\n={10,}\s*$', '', file_content.rstrip()) + "\n"

        target_path = os.path.join(target_dir, rel_path)
        is_new = not os.path.exists(target_path)

        if dry_run:
            status = "[NEW]" if is_new else "[OVERWRITE]"
            print(f"{status} {rel_path} ({len(file_content)} chars)")
        else:
            os.makedirs(os.path.dirname(target_path), exist_ok=True)
            with open(target_path, "w", encoding="utf-8") as out:
                out.write(file_content)

            if is_new:
                created_count += 1
                print(f"[CREATED] {rel_path}")
            else:
                updated_count += 1
                print(f"[UPDATED] {rel_path}")

    print("\n" + "=" * 50)
    if dry_run:
        print(f"Dry run complete. Found {len(matches)} files.")
    else:
        print(f"Done! Created: {created_count}, Updated: {updated_count} files.")
        print("Run 'git status' or 'git diff' to review changes made by Gemini.")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Unpack a codebase .txt back into project files.")
    parser.add_argument("file", nargs="?", default="codebase_context.txt", help="Path to the .txt file")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing to disk")
    parser.add_argument("--target", default=ROOT_DIR, help="Target directory (defaults to project root)")

    args = parser.parse_args()
    unpack_codebase(os.path.abspath(args.file), target_dir=args.target, dry_run=args.dry_run)
