"""Publication Figure Composer Engine for Many-Body Physics Studio.
Directly loads raw numerical NumPy arrays from many_body_results/**/*.npz
and renders multi-panel vector-grade figures with journal dimensions,
LaTeX typography, and customizable colormaps.
"""

import os
import glob
import io
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANY_BODY_ROOT = os.path.join(PROJECT_ROOT, "many_body_results")


def find_data_files():
    """Locates all raw .npz data files generated by calculations."""
    files = {}
    pattern = os.path.join(MANY_BODY_ROOT, "**", "*.npz")
    for f in glob.glob(pattern, recursive=True):
        files[os.path.basename(f)] = f
    return files


def find_sample_plots():
    """Locates all generated .png plots."""
    plots = {}
    pattern = os.path.join(MANY_BODY_ROOT, "**", "*.png")
    for f in glob.glob(pattern, recursive=True):
        plots[os.path.basename(f)] = f
    return plots


def render_composite_figure(
    template="3-Panel Row [DOS (a) | Fermi Surface (b) | Path (c)]",
    colormap="magma",
    font_family="sans-serif",
    font_size=10,
    use_latex_ticks=True,
    width_mm=178.0
):
    """
    Renders a multi-panel publication composite figure directly from raw .npz data arrays.
    Returns (png_bytes, matplotlib_figure)
    """
    data_files = find_data_files()
    width_in = width_mm / 25.4

    # Configure publication aesthetics
    plt.rcParams.update({
        'font.size': font_size,
        'axes.labelsize': font_size + 1,
        'axes.titlesize': font_size + 1,
        'xtick.labelsize': font_size - 1,
        'ytick.labelsize': font_size - 1,
        'font.family': font_family if font_family != 'Computer Modern (LaTeX)' else 'serif',
        'mathtext.fontset': 'cm' if font_family == 'Computer Modern (LaTeX)' else 'dejavusans',
    })

    cmap_name = colormap.lower()
    if "mono" in cmap_name or "black" in cmap_name:
        cmap_name = "gray"
    elif "viridis" in cmap_name:
        cmap_name = "viridis"
    elif "plasma" in cmap_name:
        cmap_name = "plasma"
    elif "inferno" in cmap_name:
        cmap_name = "inferno"
    elif "cividis" in cmap_name:
        cmap_name = "cividis"
    else:
        cmap_name = "magma"

    # -------------------------------------------------------------------------
    # TEMPLATE 1: 3-Panel Row [DOS (a) | Fermi Surface (b) | Path (c)]
    # -------------------------------------------------------------------------
    if "3-Panel Row" in template:
        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(width_in, width_in * 0.35), constrained_layout=True)

        se_file = data_files.get("sweep_data_atJ_perp_6.0_mu_1.0.npz")
        if se_file and os.path.exists(se_file):
            d = np.load(se_file)
            omega = d['omega']
            ax1.plot(omega, d['Atot_loc_0'], color='#2563eb', lw=1.6, label=r'$J_K = 3.0$')
            ax1.plot(omega, d['Atot_loc_1'], color='#0284c7', lw=1.6, label=r'$J_K = 6.0$')
            ax1.plot(omega, d['Atot_loc_2'], color='#b91c1c', lw=1.6, label=r'$J_K = 9.0$')
            ax1.axvline(0, color='#94a3b8', ls='--', lw=0.9)
            ax1.set_xlim(-15, 15)
            ax1.set_ylim(bottom=0)
            ax1.set_title(r'\textbf{(a)} DOS $A(\omega)$' if use_latex_ticks else "(a) DOS A(w)")
            ax1.set_xlabel(r'$\omega$' if use_latex_ticks else "w")
            ax1.set_ylabel(r'$A(\omega)$' if use_latex_ticks else "A(w)")
            ax1.legend(fontsize=font_size - 2, frameon=False)

            # Panel (b): Fermi Surface
            fs_data = np.fft.fftshift(d['Atot_w0_1']).T
            im2 = ax2.imshow(fs_data, origin='lower', extent=[-np.pi, np.pi, -np.pi, np.pi], cmap=cmap_name)
            ax2.set_title(r'\textbf{(b)} Fermi Surface $A(\mathbf{k}, 0)$' if use_latex_ticks else "(b) Fermi Surface")
            ax2.set_xlabel(r'$k_x$' if use_latex_ticks else "kx")
            ax2.set_ylabel(r'$k_y$' if use_latex_ticks else "ky")
            if use_latex_ticks:
                ax2.set_xticks([-np.pi, 0, np.pi])
                ax2.set_xticklabels([r'$-\pi$', r'$0$', r'$\pi$'])
                ax2.set_yticks([-np.pi, 0, np.pi])
                ax2.set_yticklabels([r'$-\pi$', r'$0$', r'$\pi$'])
            fig.colorbar(im2, ax=ax2, shrink=0.85)

            # Panel (c): Dispersion Path
            path_data = d['Atot_path_1']
            im3 = ax3.imshow(path_data, origin='lower', aspect='auto', cmap=cmap_name, extent=[0, 3, -15, 15])
            ax3.set_title(r'\textbf{(c)} Band Dispersion $A(\mathbf{k}, \omega)$' if use_latex_ticks else "(c) Path A(k, w)")
            ax3.set_xlabel(r'Path $\Gamma \to M \to X \to \Gamma$' if use_latex_ticks else "Path G-M-X-G")
            ax3.set_ylabel(r'$\omega$' if use_latex_ticks else "w")
            if use_latex_ticks:
                ax3.set_xticks([0, 1, 2, 3])
                ax3.set_xticklabels([r'$\Gamma$', r'$M$', r'$X$', r'$\Gamma$'])
            fig.colorbar(im3, ax=ax3, shrink=0.85)
        else:
            ax1.text(0.5, 0.5, "Data not found", ha='center')

    # -------------------------------------------------------------------------
    # TEMPLATE 2: 2-Panel Comparison [Static χ(q) | Dynamic χ(q, ω)]
    # -------------------------------------------------------------------------
    elif "2-Panel Comparison" in template:
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(width_in, width_in * 0.42), constrained_layout=True)

        susc_stat = data_files.get("sweep_JK_fixed_J_6.0_mu_1.00_static.npz")
        susc_dyn = data_files.get("sweep_JK_fixed_J_6.0_mu_1.00_dynamic.npz")

        if susc_stat and os.path.exists(susc_stat):
            d1 = np.load(susc_stat)
            m = d1['static_maps'][1]  # J_K = 6.0
            im1 = ax1.imshow(m, origin='lower', extent=[-np.pi, np.pi, -np.pi, np.pi], cmap=cmap_name)
            ax1.set_title(r'\textbf{(a)} Static Susceptibility $\chi(\mathbf{q}, 0)$' if use_latex_ticks else "(a) Static Chi(q)")
            ax1.set_xlabel(r'$q_x$' if use_latex_ticks else "qx")
            ax1.set_ylabel(r'$q_y$' if use_latex_ticks else "qy")
            fig.colorbar(im1, ax=ax1, shrink=0.85)

        if susc_dyn and os.path.exists(susc_dyn):
            d2 = np.load(susc_dyn)
            spec = d2['spectral_maps'][1]
            im2 = ax2.imshow(spec, origin='lower', aspect='auto', extent=[0, 3, 0, 10], cmap=cmap_name)
            ax2.set_title(r'\textbf{(b)} Dynamic Spin Excitations $\chi(\mathbf{q}, \omega)$' if use_latex_ticks else "(b) Dynamic Chi(q, w)")
            ax2.set_xlabel(r'Wavevector $\mathbf{q}$' if use_latex_ticks else "q")
            ax2.set_ylabel(r'$\omega$' if use_latex_ticks else "w")
            if use_latex_ticks:
                ax2.set_xticks([0, 1, 2, 3])
                ax2.set_xticklabels([r'$\Gamma$', r'$M$', r'$X$', r'$\Gamma$'])
            fig.colorbar(im2, ax=ax2, shrink=0.85)

    # -------------------------------------------------------------------------
    # TEMPLATE 3: 2x2 Full Suite [DOS | FS | Path | Phase Diagram]
    # -------------------------------------------------------------------------
    elif "2x2" in template:
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(width_in, width_in * 0.8), constrained_layout=True)

        se_file = data_files.get("sweep_data_atJ_perp_6.0_mu_1.0.npz")
        pd_file = data_files.get("phase_diagram_mu1.00_AFM.npz")

        if se_file and os.path.exists(se_file):
            d = np.load(se_file)
            ax1.plot(d['omega'], d['Atot_loc_1'], color='#2563eb', lw=1.6)
            ax1.set_xlim(-15, 15)
            ax1.set_title(r'\textbf{(a)} Density of States $A(\omega)$')
            ax1.set_xlabel(r'$\omega$'); ax1.set_ylabel(r'$A(\omega)$')

            im2 = ax2.imshow(np.fft.fftshift(d['Atot_w0_1']).T, origin='lower', extent=[-np.pi, np.pi, -np.pi, np.pi], cmap=cmap_name)
            ax2.set_title(r'\textbf{(b)} Fermi Surface $A(\mathbf{k}, 0)$')
            ax2.set_xlabel(r'$k_x$'); ax2.set_ylabel(r'$k_y$')
            fig.colorbar(im2, ax=ax2, shrink=0.85)

            im3 = ax3.imshow(d['Atot_path_1'], origin='lower', aspect='auto', cmap=cmap_name, extent=[0, 3, -15, 15])
            ax3.set_title(r'\textbf{(c)} Dispersion $A(\mathbf{k}, \omega)$')
            ax3.set_xlabel(r'Path $\mathbf{k}$'); ax3.set_ylabel(r'$\omega$')
            fig.colorbar(im3, ax=ax3, shrink=0.85)

        if pd_file and os.path.exists(pd_file):
            dpd = np.load(pd_file)
            ax4.plot(dpd['JK_values'], dpd['qc_winner'], color='#15803d', lw=2.0)
            ax4.set_title(r'\textbf{(d)} Phase Boundary $J_c(J_K)$')
            ax4.set_xlabel(r'Kondo Exchange $J_K$'); ax4.set_ylabel(r'Critical Interlayer $J_c$')
            ax4.grid(True, alpha=0.3)

    # -------------------------------------------------------------------------
    # TEMPLATE 4: 1x1 Single Focus Figure
    # -------------------------------------------------------------------------
    else:
        fig, ax = plt.subplots(figsize=(width_in, width_in * 0.6), constrained_layout=True)
        se_file = data_files.get("both_JK_fixed_Jperp6.00_k_1_0_mu1.00.npz")
        if se_file and os.path.exists(se_file):
            d = np.load(se_file)
            omega = d['omega']
            ax.plot(omega, d['A_k_0'], label=r'$J_K = 3.0$', lw=1.8, color='#2563eb')
            ax.plot(omega, d['A_k_1'], label=r'$J_K = 6.0$', lw=1.8, color='#0284c7')
            ax.plot(omega, d['A_k_2'], label=r'$J_K = 9.0$', lw=1.8, color='#b91c1c')
            ax.set_xlim(-15, 15)
            ax.set_title(r'Quasiparticle Spectral Function $A(\mathbf{k}_F, \omega)$ at Antinode $(\pi, 0)$')
            ax.set_xlabel(r'$\omega$'); ax.set_ylabel(r'$A(\mathbf{k}, \omega)$')
            ax.legend(frameon=False)

    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=160)
    buf.seek(0)
    img_bytes = buf.getvalue()
    buf.close()

    return img_bytes, fig


def get_latex_snippet(template):
    """Returns copy-paste ready LaTeX code snippet."""
    return r"""\begin{figure}[tbp]
    \centering
    \includegraphics[width=\columnwidth]{thesis_composite_figure.pdf}
    \caption{\textbf{Heavy-fermion spectral weight transfer and magnetic instability in metal-Mott heterostructures.}
    (a) Total electron density of states $A(\omega)$ showing peak suppression at the Fermi level.
    (b) Fermi surface intensity map $A(\mathbf{k}, \omega=0)$ across $[-\pi, \pi]^2$.
    (c) Energy-momentum dispersion along the high-symmetry path $\Gamma \to M \to X \to \Gamma$.
    (d) Exact phase boundary curve $J_c(J_K)$ separating the paramagnetic Fermi liquid from magnetic order.}
    \label{fig:heavy_fermion_destruction}
\end{figure}"""
